# ==============================================================
# Enables the debug mode. Used for troubleshooting when problems appear.
# ==============================================================
debug_mode: false

configuration:
  # General configuration needed for this program to run.


  # ====================================================
  # Specifies the service. Valid options: gitlab, github
  # ====================================================
  service: gitlab

  # =============================================================================================
  # Also known as "Secret" must be the same as in Webhook configuration depending on your service
  # =============================================================================================
  token: some

  # =======================================
  # The port that is used for this program.
  # =======================================
  port: 750

  # =======================================================
  # Command that should be used when an pull request comes. git -C /dir/dir pull origin
  # =======================================================
  command_pull: ls


additional_configuration:
  # NOT IMPLEMENTED YET
  # Additional confuguration


  push:
    # =======================
    # Enables the push option
    # =======================
    enabled:  true

    # =======================================================
    # Command that should be used when an push request comes.
    # =======================================================
    command_push: git -C /dir/dir push origin

discord_interaction:
  # NOT IMPLEMENTED YET!
  # Discord Interaction configuration
  # * lets you execute pull and push on press of an button in message send by built-in bot


  # =====================================================================================================
  # Enables / Disables this function
  # =====================================================================================================
  enabled: true

  # =====================================================================================================
  # Bot token needed to run the bot. Can be found on discord developers
  # =====================================================================================================
  bot_token: bot token

  # =====================================================================================================
  # Specifies if the bot should send logs (start,pushing,pulling,failed,unauthorized request)
  # =====================================================================================================
  logs: true