# ==============================================================
# Enables the debug mode. Used for troubleshooting when problems appear.
# ==============================================================
debug_mode: false

configuration:
  # General configuration needed for this program to run.


  # ====================================================
  # Specifies the service. Valid options: gitlab, github
  # ====================================================
  service: github

  # =============================================================================================
  # Also known as "Secret" must be the same as in Webhook configuration depending on your service
  # =============================================================================================
  token: SUS123

  # =======================================
  # The port that is used for this program.
  # =======================================
  port: 750

  # =======================================================
  # Command that should be used when an pull request comes. git -C /dir/dir pull origin
  # =======================================================
  command_pull: a

discord_interaction:
  # Discord Interaction configuration
  # Webhook notifications


  # =====================================================================================================
  # Enables / Disables this function
  # =====================================================================================================
  enabled: true

  # =====================================================================================================
  # Webhook url. Can be created in the Discord server settings.
  # =====================================================================================================
  webhookurl: https://discord.com/api/webhooks/879660573795708928/W5T89WaSXvWEMqLbRcdPIGvK2DW2GB1AdmjZzecwB-VFM2Zc7XAVe8Dt_uTJrW6gLrke